name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        version: 10
    
    - name: install dependencies, test and build the app
      run: |
        npm install
        npm test
        npm run build
        
    - name: dockerize and publish the app
      uses: actions-hub/docker@v1.0.0
