name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: bitoiu/node-js-action-template@v1.0
    - run: |
        ls
        echo ${KUBECONFIG}
        npm install
        npm test
        npm run build
        docker login -u ${} -p ${} ...
        docker build -t github.com/mabotn/actions-experiment .
        docker push -t github.com/mabotn/actions-experiment
    
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: danielr1996/kubectl-action@1.0.0
        with:
          kubeconfig: abc
      - run: |
          kubectl apply -f deploy/
          kubectl patch ... 

